---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-task
  annotations:
    tekton.dev/displayName: Echo Task Test
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/tags: echo, task, test
  labels:
    app.kubernetes.io/version: "0.1"  
spec:
  params:
    - name: str
      type: string
      description: String to echo
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi@sha256:66233eebd72bb5baa25190d4f55e1dc3fff3a9b77186c1f91a0abdb274452072
      volumeMounts:
        - name: workdir
          mountPath: "$(params.workdir)"
        - name: trusted-ca
          mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          subPath: ca-bundle.crt
          readOnly: true
      env:
        - name: STR
          value: "$(params.str)"
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail

        echo "$(STR)"
