---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: first-task
  annotations:
    tekton.dev/displayName: "first task"
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/tags: echo, task, test
    artifacthub.io/provider: Avi
    artifacthub.io/category: integration-delivery
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    First task for tests v1
  params:
    - name: mystr
      type: string
      description: String to echo
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi@sha256:66233eebd72bb5baa25190d4f55e1dc3fff3a9b77186c1f91a0abdb274452072
      env:
        - name: STR
          value: "$(params.mystr)"
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail
  
        echo "${STR}"
