---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: tasks
  namespace: managed-ns2
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - tasks
  data:
    mapping:
      components:
      - name: echo-v01
        repository: quay.io/avi_test/user-ns2/release-catalog/task-echo
        tags:
        - "0.1"
      - name: echo-v02
        repository: quay.io/avi_test/user-ns2/release-catalog/task-echo
        tags:
        - "0.2"
      - name: echo-v03
        repository: quay.io/avi_test/user-ns2/release-catalog/task-echo
        tags:
        - "0.3"
      - name: yet-another-v01
        repository: quay.io/avi_test/user-ns2/release-catalog/task-yet-another
        tags:
        - "0.1"

  origin: user-ns2
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/avi-biton/release-service-catalog.git"
        - name: revision
          value: release-test
        - name: pathInRepo
          value: "pipelines/managed/push-bundle-to-external-registry/push-bundle-to-external-registry.yaml"
    serviceAccountName: appstudio-pipeline
  policy: default
